# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: credit_analysis_tool.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'credit_analysis_tool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63redit_analysis_tool.proto\x12\x03\x61pp\"\xa2\x01\n\nGenRequest\x12\x14\n\x0cpubGloblJnno\x18\x01 \x01(\t\x12\x0e\n\x06seriNo\x18\x02 \x01(\t\x12\x10\n\x08reportId\x18\x03 \x01(\t\x12\x13\n\x0b\x63ompanyName\x18\x04 \x01(\t\x12\x13\n\x0bhtmlSdossId\x18\x05 \x01(\t\x12\x11\n\tcreatUser\x18\x06 \x01(\t\x12\x1f\n\x08reqFiles\x18\x07 \x03(\x0b\x32\r.app.ReqFiles\"-\n\x08ReqFiles\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0f\n\x07\x66ileUrl\x18\x02 \x01(\t\"\x96\x03\n\x08GenReply\x12\x10\n\x08tranCode\x18\x01 \x01(\t\x12\x0e\n\x06\x63hanId\x18\x02 \x01(\t\x12\r\n\x05sysId\x18\x03 \x01(\t\x12\x14\n\x0cpubGloblJnno\x18\x04 \x01(\t\x12\x0e\n\x06seriNo\x18\x05 \x01(\t\x12\x12\n\nreqBizDate\x18\x06 \x01(\t\x12\x13\n\x0btranCounter\x18\x07 \x01(\t\x12\r\n\x05orgNo\x18\x08 \x01(\t\x12\x10\n\x08protocol\x18\t \x01(\t\x12\x16\n\x0epreReverseFlag\x18\n \x01(\t\x12\x11\n\tlegalCode\x18\x0b \x01(\t\x12\x11\n\theadVerNo\x18\x0c \x01(\t\x12\x10\n\x08preSysId\x18\r \x01(\t\x12\x13\n\x0bpreSerialNo\x18\x0e \x01(\t\x12\x13\n\x0bpreReqVerNo\x18\x0f \x01(\t\x12\x12\n\npreSubFlag\x18\x10 \x01(\t\x12\x10\n\x08reportId\x18\x11 \x01(\t\x12\x0f\n\x07\x64\x65\x61lSts\x18\x12 \x01(\t\x12\x12\n\ndealRemark\x18\x13 \x01(\t\x12$\n\x0breportFiles\x18\x14 \x03(\x0b\x32\x0f.app.ReportFile\"/\n\nReportFile\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0f\n\x07sdossId\x18\x02 \x01(\t2M\n\x0fReportGenerator\x12:\n\x18gen_credit_analysis_tool\x12\x0f.app.GenRequest\x1a\r.app.GenReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credit_analysis_tool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENREQUEST']._serialized_start=36
  _globals['_GENREQUEST']._serialized_end=198
  _globals['_REQFILES']._serialized_start=200
  _globals['_REQFILES']._serialized_end=245
  _globals['_GENREPLY']._serialized_start=248
  _globals['_GENREPLY']._serialized_end=654
  _globals['_REPORTFILE']._serialized_start=656
  _globals['_REPORTFILE']._serialized_end=703
  _globals['_REPORTGENERATOR']._serialized_start=705
  _globals['_REPORTGENERATOR']._serialized_end=782
# @@protoc_insertion_point(module_scope)
