# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import credit_analysis_tool_pb2 as credit__analysis__tool__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in credit_analysis_tool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportGeneratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.gen_credit_analysis_tool = channel.unary_unary(
                '/app.ReportGenerator/gen_credit_analysis_tool',
                request_serializer=credit__analysis__tool__pb2.GenRequest.SerializeToString,
                response_deserializer=credit__analysis__tool__pb2.GenReply.FromString,
                _registered_method=True)


class ReportGeneratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def gen_credit_analysis_tool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'gen_credit_analysis_tool': grpc.unary_unary_rpc_method_handler(
                    servicer.gen_credit_analysis_tool,
                    request_deserializer=credit__analysis__tool__pb2.GenRequest.FromString,
                    response_serializer=credit__analysis__tool__pb2.GenReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.ReportGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.ReportGenerator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportGenerator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def gen_credit_analysis_tool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.ReportGenerator/gen_credit_analysis_tool',
            credit__analysis__tool__pb2.GenRequest.SerializeToString,
            credit__analysis__tool__pb2.GenReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
